### ISSUE TITLE
How to realize multi-view rendering in bpy rendering?

### ISSUE THREAD

**Issue by delaprada** [adwardlee/RenderIH#1]
Hi, thank you for providing this good work.

May I ask how to realize multi-view rendering in bpy rendering. I read the code in `step4_load_mano_diffbg.py`. I saw there are codes decoding the K, R, T from P, but when adding the camera to the scene, these R, T information are not used here:

https://github.com/adwardlee/RenderIH/blob/5ac36701f935f4110087f5981872516073992b1e/rendering_code/step4_load_mano_diffbg.py#L156-L233

I am also curious about how to obtain the initial value of P. Is it exported from Blender, or is it manually predefined?

Thank you!

**Comment by adwardlee** [comment]
Hi @delaprada,

Thanks for your interest. Previously, the camera parameter is defined in the scripts but it leads to some misalignments in rendering and definition. Then the camera parameters is predefined in the `0826.blend` which can be seen in `materials.zip`. Moreover, the initial camera parameter P is acquired from the Interhand2.6M.

**Comment by asvaling** [comment]
Hi @adwardlee. Thanks for your great work. I wonder how to access `materials.zip`? The link in the readme requires application for access permission. I tried to apply but did not get a reply.

**Comment by delaprada** [comment]
> Hi @delaprada,
> 
> Thanks for your interest. Previously, the camera parameter is defined in the scripts but it leads to some misalignments in rendering and definition. Then the camera parameters is predefined in the `0826.blend` which can be seen in `materials.zip`. Moreover, the initial camera parameter P is acquired from the Interhand2.6M.

I see. Thank you! It seems that the script will call the `0826.blend` file to execute rendering every time.

**Comment by adwardlee** [comment]
> Hi @adwardlee. Thanks for your great work. I wonder how to access `materials.zip`? The link in the readme requires application for access permission. I tried to apply but did not get a reply.

The file is shared publicly now. Thanks.
