### ISSUE TITLE
Source code for Augmented Pose and Optimization

### ISSUE THREAD

**Issue by ZhangMenghe** [adwardlee/RenderIH#5]
Hi, thanks for the great work! I was wondering if you have already published the code for augmenting the poses and IH Pose optimization code (e.g. anti-penetration, attraction, anatomic loss, etc)?

**Comment by adwardlee** [comment]
Hi @ZhangMenghe,

The code for augmenting and optimization is not available yet. It may be released in a few weeks. Thanks.

**Comment by adwardlee** [comment]
Hi @ZhangMenghe,

The code for augmenting poses and optimization is updated in [https://github.com/adwardlee/RenderIH/tree/main/pose_data_optimize](url)
