### ISSUE TITLE
TransHand 

### ISSUE THREAD

**Issue by liangshenglei** [adwardlee/RenderIH#7]
Hello.
Very helpful paper, I am very interested in the TransHand in it. The intertwining of left and right hand features is very useful. But I didn't sort out the structure of the code and didn't find the corresponding code, can you tell me exactly in those papers?
Thank you very much, I look forward to your reply and wish you a happy new year in advance!

**Comment by adwardlee** [comment]
Hi @liangshenglei,

Thanks for your interest. The interaction of two hand features can be seen in [class inter_attn](https://github.com/adwardlee/RenderIH/blob/main/common/myhand/model_attn/inter_attn_lijun.py#L38).
