### ISSUE TITLE
Code for TSNE visualization

### ISSUE THREAD

**Issue by aswathselvam** [adwardlee/RenderIH#8]
Do you have a code release for the TSNE pose distribution visualization? 
<img width="580" alt="image" src="https://github.com/adwardlee/RenderIH/assets/7314342/1acf83fc-343e-4523-8a01-507fc1931d52">

**Comment by adwardlee** [comment]
Sorry, the code is not available because the project is from a long time ago. An example can be found at https://github.com/pavlin-policar/openTSNE. Thanks.
